In [1]:
import lab_1

In [2]:
log_file_name=[[],[]]
matrix_file_name=[[],[]]

exp_2={'13':['500','450','400','350'],
           '17':['600','550','500','450','400']}
for i in exp_2['13']:
        log_file_name[0].append(f'log_{13}_keys_{i}_ms.csv')
        matrix_file_name[0].append(f'matrix_{13}_keys_{i}_ms.csv')
for i in exp_2['17']:
    log_file_name[1].append(f'log_{17}_keys_{i}_ms.csv')
    matrix_file_name[1].append(f'matrix_{17}_keys_{i}_ms.csv')

#форматируем файлы
for log in log_file_name[0]:
    lab_1.file_formatting(f'data_exp_2/{13}_keys/{log}')
for matrix in matrix_file_name[0]:
    lab_1.file_formatting(f'data_exp_2/{13}_keys/{matrix}')

#считываем данные с файлов и убираем выбросы и неверные нажатия
log=[]
for file_name in log_file_name[0]:
    log.append(lab_1.np.loadtxt(f'data_exp_2/{13}_keys/{file_name}', delimiter=","))
matrix=[]
for file_name in matrix_file_name[0]:
     matrix.append(lab_1.np.loadtxt(f'data_exp_2/{13}_keys/{file_name}', delimiter=","))

info_channel_diagram=[]
for m in matrix:
    print(m)
    info_channel_diagram.append(lab_1.info_channel_diagram_count(m))
print(info_channel_diagram)

[[3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 3.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]
 [0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0. 0. 0. 0